### PR TITLE
it's a passing build

### PR DESCRIPTION
**Pull request by asxrow66**
idk if it will work but worth a shot

### CODE REVIEW

**Comment by asxrow66** [comment]
let it see if it builds first

**Comment by asxrow66** [comment]
https://github.com/asxrow66/Engine/actions/runs/10034533776 but i would still want it to be built in this pr

**Comment by JoshBashed** [comment]
I have no idea what you are doing.

This PR changes GPTK back to version one. We don't want to do that. Unless you can explain what you are doing, I am closing this.

**Comment by asxrow66** [comment]
Then fix it yourself dude. You release a shitty update and then dip the entire project and don't do or say anything. You can't admit you fucked up and you fucked up the engine. Apple didn't deprecate shit, you just released a shitty update and can't admit shit. Whisky is working completely fine, you didn't fuck up their engine. I accidentally commited GPTK 1 and I'll admit it, you can't admit your mistake which has been tried to be reverted but still fails. Why did you even commit a failed build in the first place???

**Pull request closed without merging**
